version: "3"

services:
  nginx:
    depends_on:
      - client
      - backend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: proman-nginx:latest
    ports:
      - "80:80"

  client:
    build:
      context: ./frontend
    image: proman-frontend:latest
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    restart: on-failure
    # depends_on:
    #   - backend

  backend:
    build:
      context: ./backend
    image: proman-backend:latest
    ports:
      - "8000:8000"
    environment:
      - PGUSER=proman
      - PGHOST=postgres
      - PGDATABASE=proman
      - PGPASSWORD=ZIhLFAJGHk66ukMIYchE
      - PGPORT=5432
