version: "3"

services:
  nginx:
    depends_on:
      - client
      - backend
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"

  client:
    build:
      context: ./frontend
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    restart: on-failure
    # depends_on:
    #   - backend
  backend:
    build:
      context: ./src
    command: gunicorn cosmetica.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - PGUSER=proman
      - PGHOST=postgres
      - PGDATABASE=proman
      - PGPASSWORD=ZIhLFAJGHk66ukMIYchE
      - PGPORT=5432
