version: "3"

services:
  backend:
    build:
      context: ./src
    command: gunicorn cosmetica.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - PGUSER=proman
      - PGHOST=postgres
      - PGDATABASE=proman
      - PGPASSWORD=ZIhLFAJGHk66ukMIYchE
      - PGPORT=5432

  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/react/build
    # depends_on:
    #   - backend
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
volumes:
  react_build:
