# Generated by Django 3.2 on 2021-09-22 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_paymentinfo_model_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='model_number',
            new_name='order_number',
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
