# Generated by Django 3.2 on 2021-09-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210922_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.paymentinfo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('failed', 'Failed'), ('shipped', 'Shipped'), ('refund', 'Refund'), ('confirm', 'Confirm'), ('picked_by_delivery', 'picked_by_delivery'), ('delivery_complete', 'delivery_complete')], max_length=64, null=True),
        ),
    ]
