# Generated by Django 3.2 on 2021-09-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210926_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paymentinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='paymentinfo',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
