# Generated by Django 3.2 on 2021-12-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210926_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('confirm', 'Confirm'), ('order_processing', 'order_processing'), ('picked_by_delivery', 'picked_by_delivery'), ('delivery_complete', 'delivery_complete'), ('failed', 'Failed'), ('refund', 'Refund')], max_length=64, null=True),
        ),
    ]
