# Generated by Django 3.2 on 2021-12-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ecourier_tracker_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
