# Generated by Django 3.2 on 2021-12-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_ecourier_tracker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('created', 'created'), ('confirm', 'confirm'), ('order_processing', 'order_processing'), ('picked_by_delivery', 'picked_by_delivery'), ('delivery_complete', 'delivery_complete'), ('failed', 'Failed'), ('refund', 'Refund')], max_length=64, null=True),
        ),
    ]
