# Generated by Django 3.2 on 2021-07-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20210725_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
