# Generated by Django 3.2 on 2021-07-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.IntegerField(default=60),
        ),
    ]
