# Generated by Django 3.2 on 2021-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_free_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
