# Generated by Django 3.2 on 2021-08-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('created', 'created'), ('failed', 'failed'), ('cash_on_delivery', 'cash_on_delivery'), ('online_payment', 'online_payment'), ('shipped', 'shipped'), ('refund', 'refund'), ('confirm', 'confirm')], max_length=64, null=True),
        ),
    ]
