# Generated by Django 3.2 on 2021-08-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('created', 'Created'), ('failed', 'Failed'), ('cash_on_delivery', 'Cash on delivery'), ('online_payment', 'Online payment'), ('shipped', 'Shipped'), ('refund', 'Refund'), ('confirm', 'Confirm')], max_length=64, null=True),
        ),
    ]
