# Generated by Django 3.2 on 2021-04-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
