# Generated by Django 3.2 on 2021-07-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210611_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_delivery_time',
            field=models.IntegerField(default=2),
        ),
    ]
