# Generated by Django 3.2 on 2021-08-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_product_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='buy_one_get_one',
            field=models.BooleanField(default=False),
        ),
    ]
