# Generated by Django 3.2 on 2021-08-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_buy_one_get_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='combo_amount',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='products',
            name='combo_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('Movie', 'Movie'), ('Game', 'Game'), ('Life', 'Life'), ('Sports', 'Sports'), ('Programming', 'Programming'), ('Trend', 'Trend')], max_length=200, null=True),
        ),
    ]
