# Generated by Django 3.2 on 2021-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210909_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='few_left',
            field=models.BooleanField(default=False),
        ),
    ]
