# Generated by Django 3.2 on 2021-09-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_dailydeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
