# Generated by Django 3.2 on 2021-07-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_auto_20210715_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
