# Generated by Django 3.2 on 2021-07-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon',
        ),
    ]
