# Generated by Django 3.2 on 2021-08-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_remove_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='buy_one_get_one',
            field=models.BooleanField(default=False),
        ),
    ]
