# Generated by Django 3.2 on 2021-08-10 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0017_cart_buy_one_get_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='expires',
        ),
        migrations.CreateModel(
            name='FinalCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.BooleanField(blank=True, null=True)),
                ('coupon', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_total', models.IntegerField(blank=True, default=0, null=True)),
                ('being_delivered', models.BooleanField(default=False)),
                ('cart', models.ManyToManyField(to='cart.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
