# Generated by Django 3.2 on 2021-09-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_auto_20210810_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalcart',
            name='expires',
            field=models.BooleanField(default=False),
        ),
    ]
