# Generated by Django 3.2 on 2021-06-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='apartment_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
