# Generated by Django 3.2 on 2021-07-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_address_inside_dahaka_or_outside_dhaka'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
