export const FETCH_BEST_SELLING = "FETCH_BEST_SELLING";

export const OTP_VERIFY_START = "OTP_VERIFY_START";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
export const OTP_VERIFY_ERROR = "OTP_VERIFY_SUCCESS";

export const OTP_SEND_START = "OTP_SEND_START";
export const OTP_SEND_SUCCESS = "OTP_SEND_SUCCESS";
export const OTP_SEND_ERROR = "OTP_SEND_SUCCESS";

export const TOGGLE_SIDEBAR_OPEN = "TOGGLE_SIDEBAR_OPEN";
export const TOGGLE_SIDEBAR_CLOSE = "TOGGLE_SIDEBAR_CLOSE";

export const TOGGLE_SIDEBAR_OPEN_TWO = "TOGGLE_SIDEBAR_OPEN_TWO";
export const TOGGLE_SIDEBAR_CLOSE_TWO = "TOGGLE_SIDEBAR_CLOSE_TWO";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SHOW_OPTION = "SHOW_OPTION";
export const HIDE_OPTION = "HIDE_OPTION";

export const PROFILE_FETCH_START = "PROFILE_FETCH_START";
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS";
export const PROFILE_EDIT_ERROR = "PROFILE_EDIT_ERROR";

export const WISH_LIST_CREATE_START = "WISH_LIST_CREATE_START";
export const WISH_LIST_CREATE_SUCCESS = "WISH_LIST_CREATE_SUCCESS";
export const WISH_LIST_CREATE_ERROR = "WISH_LIST_CREATE_ERROR";
export const WISH_LIST_CREATE_FETCH_START = "WISH_LIST_CREATE_FETCH_START";
export const WISH_LIST_CREATE_FETCH_SUCCESS = "WISH_LIST_CREATE_FETCH_SUCCESS";
export const WISH_LIST_CREATE_FETCH_ERROR = "WISH_LIST_CREATE_FETCH_ERROR";
export const WISH_LIST_DELETE_START = "WISH_LIST_DELETE_START";
export const WISH_LIST_DELETE_SUCCESS = "WISH_LIST_DELETE_SUCCESS";
export const WISH_LIST_DELETE_ERROR = "WISH_LIST_DELETE_ERROR";
