export const FETCH_BEST_SELLING = "FETCH_BEST_SELLING";

export const OTP_VERIFY_START = "OTP_VERIFY_START";
export const OTP_VERIFY_SUCCESS = "OTP_VERIFY_SUCCESS";
export const OTP_VERIFY_ERROR = "OTP_VERIFY_SUCCESS";

export const OTP_SEND_START = "OTP_SEND_START";
export const OTP_SEND_SUCCESS = "OTP_SEND_SUCCESS";
export const OTP_SEND_ERROR = "OTP_SEND_SUCCESS";

export const TOGGLE_SIDEBAR_OPEN = "TOGGLE_SIDEBAR_OPEN";
export const TOGGLE_SIDEBAR_CLOSE = "TOGGLE_SIDEBAR_CLOSE";
