export const FETCH_USER_CART = "FETCH_USER_CART";
export const FETCH_USER_CART_ERROR = "FETCH_USER_CART_ERROR";

export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

export const DELETE_FROM_CART_START = "DELETE_FROM_CART_START";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const DELETE_FROM_CART_ERROR = "DELETE_FROM_CART_ERROR";
