export const FETCH_USER_CART = "FETCH_USER_CART";
export const FETCH_USER_CART_ERROR = "FETCH_USER_CART_ERROR";

export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";

export const FETCH_PRICING_DETAILS_STATRT = "FETCH_PRICING_DETAILS_STATRT";
export const FETCH_PRICING_DETAILS_SUCCESS = "FETCH_PRICING_DETAILS_SUCCESS";
export const FETCH_PRICING_DETAILS_ERROR = "FETCH_PRICING_DETAILS_ERROR";

export const DELETE_FROM_CART_START = "DELETE_FROM_CART_START";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const DELETE_FROM_CART_ERROR = "DELETE_FROM_CART_ERROR";

export const APPLY_COUPON_START = "APPLY_COUPON_START";
export const APPLY_COUPON_SUCCESS = "APPLY_COUPON_SUCCESS";
export const APPLY_COUPON_ERROR = "APPLY_COUPON_ERROR";

export const OPEN_SIDEBAR_CART = "OPEN_SIDEBAR_CART";
export const CLOSE_SIDEBAR_CART = "CLOSE_SIDEBAR_CART";
