# Generated by Django 3.2 on 2021-04-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210419_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
