# Generated by Django 3.2 on 2021-04-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='short_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
