# Generated by Django 3.2 on 2021-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='l_size',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='m_size',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='s_size',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='xl_size',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='xxl_size',
            field=models.BooleanField(default=True),
        ),
    ]
