# Generated by Django 3.2 on 2021-09-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='demo@example.com', max_length=254)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=200, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('meesage', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
