# Generated by Django 3.2 on 2021-12-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20211225_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet_amount_usable',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='users_free_delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserGameActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_validity', models.DateTimeField()),
                ('reward_value', models.IntegerField()),
                ('game_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile')),
            ],
        ),
    ]
