# Generated by Django 3.2 on 2021-05-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('orders', '0007_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ManyToManyField(to='address.Address'),
        ),
    ]
